package com.example.mushaf.domain.model

enum class SurahOrigin { MECCAN, MEDINAN }

data class Surah(
    val number: Int,
    val nameArabic: String,
    val nameEnglish: String,
    val origin: SurahOrigin,
    val nameAr: String = nameArabic,
    val nameEn: String = nameEnglish,
    val revelationType: String = origin.name,
    val verseCount: Int = 0
)

/**
 * Compile-time catalogue of all 114 surahs with Arabic names, English transliterations,
 * and Meccan/Medinan origin — used for the Surah Picker bottom sheet.
 */
object SurahCatalog {

    val all: List<Surah> = listOf(
        Surah(1,   "الفَاتِحَة",   "Al-Fatihah",    SurahOrigin.MECCAN, verseCount = 7),
        Surah(2,   "البَقَرَة",    "Al-Baqarah",    SurahOrigin.MEDINAN, verseCount = 286),
        Surah(3,   "آل عِمرَان",  "Ali 'Imran",    SurahOrigin.MEDINAN, verseCount = 200),
        Surah(4,   "النِّسَاء",    "An-Nisa",       SurahOrigin.MEDINAN, verseCount = 176),
        Surah(5,   "المَائِدَة",   "Al-Ma'idah",    SurahOrigin.MEDINAN, verseCount = 120),
        Surah(6,   "الأَنعَام",    "Al-An'am",      SurahOrigin.MECCAN, verseCount = 165),
        Surah(7,   "الأَعرَاف",    "Al-A'raf",      SurahOrigin.MECCAN, verseCount = 206),
        Surah(8,   "الأَنفَال",    "Al-Anfal",      SurahOrigin.MEDINAN, verseCount = 75),
        Surah(9,   "التَّوبَة",    "At-Tawbah",     SurahOrigin.MEDINAN, verseCount = 129),
        Surah(10,  "يُونُس",       "Yunus",         SurahOrigin.MECCAN, verseCount = 109),
        Surah(11,  "هُود",         "Hud",           SurahOrigin.MECCAN, verseCount = 123),
        Surah(12,  "يُوسُف",       "Yusuf",         SurahOrigin.MECCAN, verseCount = 111),
        Surah(13,  "الرَّعد",      "Ar-Ra'd",       SurahOrigin.MEDINAN, verseCount = 43),
        Surah(14,  "إِبرَاهِيم",   "Ibrahim",       SurahOrigin.MECCAN, verseCount = 52),
        Surah(15,  "الحِجر",       "Al-Hijr",       SurahOrigin.MECCAN, verseCount = 99),
        Surah(16,  "النَّحل",      "An-Nahl",       SurahOrigin.MECCAN, verseCount = 128),
        Surah(17,  "الإِسرَاء",    "Al-Isra",       SurahOrigin.MECCAN, verseCount = 111),
        Surah(18,  "الكَهف",       "Al-Kahf",       SurahOrigin.MECCAN, verseCount = 110),
        Surah(19,  "مَريَم",       "Maryam",        SurahOrigin.MECCAN, verseCount = 98),
        Surah(20,  "طه",           "Ta-Ha",         SurahOrigin.MECCAN, verseCount = 135),
        Surah(21,  "الأَنبِيَاء",  "Al-Anbiya",     SurahOrigin.MECCAN, verseCount = 112),
        Surah(22,  "الحَج",        "Al-Hajj",       SurahOrigin.MEDINAN, verseCount = 78),
        Surah(23,  "المُؤمِنُون",  "Al-Mu'minun",   SurahOrigin.MECCAN, verseCount = 118),
        Surah(24,  "النُّور",      "An-Nur",        SurahOrigin.MEDINAN, verseCount = 64),
        Surah(25,  "الفُرقَان",    "Al-Furqan",     SurahOrigin.MECCAN, verseCount = 77),
        Surah(26,  "الشُّعَرَاء",  "Ash-Shu'ara",   SurahOrigin.MECCAN, verseCount = 227),
        Surah(27,  "النَّمل",      "An-Naml",       SurahOrigin.MECCAN, verseCount = 93),
        Surah(28,  "القَصَص",      "Al-Qasas",      SurahOrigin.MECCAN, verseCount = 88),
        Surah(29,  "العَنكَبُوت",  "Al-'Ankabut",   SurahOrigin.MECCAN, verseCount = 69),
        Surah(30,  "الرُّوم",      "Ar-Rum",        SurahOrigin.MECCAN, verseCount = 60),
        Surah(31,  "لُقمَان",      "Luqman",        SurahOrigin.MECCAN, verseCount = 34),
        Surah(32,  "السَّجدَة",    "As-Sajdah",     SurahOrigin.MECCAN, verseCount = 30),
        Surah(33,  "الأَحزَاب",    "Al-Ahzab",      SurahOrigin.MEDINAN, verseCount = 73),
        Surah(34,  "سَبَأ",         "Saba",          SurahOrigin.MECCAN, verseCount = 54),
        Surah(35,  "فَاطِر",       "Fatir",         SurahOrigin.MECCAN, verseCount = 45),
        Surah(36,  "يس",           "Ya-Sin",        SurahOrigin.MECCAN, verseCount = 83),
        Surah(37,  "الصَّافَّات",  "As-Saffat",     SurahOrigin.MECCAN, verseCount = 182),
        Surah(38,  "ص",            "Sad",           SurahOrigin.MECCAN, verseCount = 88),
        Surah(39,  "الزُّمَر",     "Az-Zumar",      SurahOrigin.MECCAN, verseCount = 75),
        Surah(40,  "غَافِر",       "Ghafir",        SurahOrigin.MECCAN, verseCount = 85),
        Surah(41,  "فُصِّلَت",     "Fussilat",      SurahOrigin.MECCAN, verseCount = 54),
        Surah(42,  "الشُّورَى",    "Ash-Shura",     SurahOrigin.MECCAN, verseCount = 53),
        Surah(43,  "الزُّخرُف",    "Az-Zukhruf",    SurahOrigin.MECCAN, verseCount = 89),
        Surah(44,  "الدُّخَان",    "Ad-Dukhan",     SurahOrigin.MECCAN, verseCount = 59),
        Surah(45,  "الجَاثِيَة",   "Al-Jathiyah",   SurahOrigin.MECCAN, verseCount = 37),
        Surah(46,  "الأَحقَاف",    "Al-Ahqaf",      SurahOrigin.MECCAN, verseCount = 35),
        Surah(47,  "مُحَمَّد",     "Muhammad",      SurahOrigin.MEDINAN, verseCount = 38),
        Surah(48,  "الفَتح",       "Al-Fath",       SurahOrigin.MEDINAN, verseCount = 29),
        Surah(49,  "الحُجُرَات",   "Al-Hujurat",    SurahOrigin.MEDINAN, verseCount = 18),
        Surah(50,  "ق",            "Qaf",           SurahOrigin.MECCAN, verseCount = 45),
        Surah(51,  "الذَّارِيَات", "Adh-Dhariyat",  SurahOrigin.MECCAN, verseCount = 60),
        Surah(52,  "الطُّور",      "At-Tur",        SurahOrigin.MECCAN, verseCount = 49),
        Surah(53,  "النَّجم",      "An-Najm",       SurahOrigin.MECCAN, verseCount = 62),
        Surah(54,  "القَمَر",      "Al-Qamar",      SurahOrigin.MECCAN, verseCount = 55),
        Surah(55,  "الرَّحمَن",    "Ar-Rahman",     SurahOrigin.MEDINAN, verseCount = 78),
        Surah(56,  "الوَاقِعَة",   "Al-Waqi'ah",    SurahOrigin.MECCAN, verseCount = 96),
        Surah(57,  "الحَدِيد",     "Al-Hadid",      SurahOrigin.MEDINAN, verseCount = 29),
        Surah(58,  "المُجَادِلَة", "Al-Mujadila",   SurahOrigin.MEDINAN, verseCount = 22),
        Surah(59,  "الحَشر",       "Al-Hashr",      SurahOrigin.MEDINAN, verseCount = 24),
        Surah(60,  "المُمتَحَنَة", "Al-Mumtahanah", SurahOrigin.MEDINAN, verseCount = 13),
        Surah(61,  "الصَّف",       "As-Saf",        SurahOrigin.MEDINAN, verseCount = 14),
        Surah(62,  "الجُمُعَة",    "Al-Jumu'ah",    SurahOrigin.MEDINAN, verseCount = 11),
        Surah(63,  "المُنَافِقُون","Al-Munafiqun",  SurahOrigin.MEDINAN, verseCount = 11),
        Surah(64,  "التَّغَابُن",  "At-Taghabun",   SurahOrigin.MEDINAN, verseCount = 18),
        Surah(65,  "الطَّلَاق",    "At-Talaq",      SurahOrigin.MEDINAN, verseCount = 12),
        Surah(66,  "التَّحرِيم",   "At-Tahrim",     SurahOrigin.MEDINAN, verseCount = 12),
        Surah(67,  "المُلك",       "Al-Mulk",       SurahOrigin.MECCAN, verseCount = 30),
        Surah(68,  "القَلَم",      "Al-Qalam",      SurahOrigin.MECCAN, verseCount = 52),
        Surah(69,  "الحَاقَّة",    "Al-Haqqah",     SurahOrigin.MECCAN, verseCount = 52),
        Surah(70,  "المَعَارِج",   "Al-Ma'arij",    SurahOrigin.MECCAN, verseCount = 44),
        Surah(71,  "نُوح",         "Nuh",           SurahOrigin.MECCAN, verseCount = 28),
        Surah(72,  "الجِن",        "Al-Jinn",       SurahOrigin.MECCAN, verseCount = 28),
        Surah(73,  "المُزَّمِّل",  "Al-Muzzammil",  SurahOrigin.MECCAN, verseCount = 20),
        Surah(74,  "المُدَّثِّر",  "Al-Muddaththir",SurahOrigin.MECCAN, verseCount = 56),
        Surah(75,  "القِيَامَة",   "Al-Qiyamah",    SurahOrigin.MECCAN, verseCount = 40),
        Surah(76,  "الإِنسَان",    "Al-Insan",      SurahOrigin.MEDINAN, verseCount = 31),
        Surah(77,  "المُرسَلَات",  "Al-Mursalat",   SurahOrigin.MECCAN, verseCount = 50),
        Surah(78,  "النَّبَأ",     "An-Naba",       SurahOrigin.MECCAN, verseCount = 40),
        Surah(79,  "النَّازِعَات", "An-Nazi'at",    SurahOrigin.MECCAN, verseCount = 46),
        Surah(80,  "عَبَس",        "'Abasa",        SurahOrigin.MECCAN, verseCount = 42),
        Surah(81,  "التَّكوِير",   "At-Takwir",     SurahOrigin.MECCAN, verseCount = 29),
        Surah(82,  "الانفِطَار",   "Al-Infitar",    SurahOrigin.MECCAN, verseCount = 19),
        Surah(83,  "المُطَفِّفِين","Al-Mutaffifin", SurahOrigin.MECCAN, verseCount = 36),
        Surah(84,  "الانشِقَاق",   "Al-Inshiqaq",   SurahOrigin.MECCAN, verseCount = 25),
        Surah(85,  "البُرُوج",     "Al-Buruj",      SurahOrigin.MECCAN, verseCount = 22),
        Surah(86,  "الطَّارِق",    "At-Tariq",      SurahOrigin.MECCAN, verseCount = 17),
        Surah(87,  "الأَعلَى",     "Al-A'la",       SurahOrigin.MECCAN, verseCount = 19),
        Surah(88,  "الغَاشِيَة",   "Al-Ghashiyah",  SurahOrigin.MECCAN, verseCount = 26),
        Surah(89,  "الفَجر",       "Al-Fajr",       SurahOrigin.MECCAN, verseCount = 30),
        Surah(90,  "البَلَد",      "Al-Balad",      SurahOrigin.MECCAN, verseCount = 20),
        Surah(91,  "الشَّمس",      "Ash-Shams",     SurahOrigin.MECCAN, verseCount = 15),
        Surah(92,  "اللَّيل",      "Al-Layl",       SurahOrigin.MECCAN, verseCount = 21),
        Surah(93,  "الضُّحَى",     "Ad-Duha",       SurahOrigin.MECCAN, verseCount = 11),
        Surah(94,  "الشَّرح",      "Ash-Sharh",     SurahOrigin.MECCAN, verseCount = 8),
        Surah(95,  "التِّين",      "At-Tin",        SurahOrigin.MECCAN, verseCount = 8),
        Surah(96,  "العَلَق",      "Al-'Alaq",      SurahOrigin.MECCAN, verseCount = 19),
        Surah(97,  "القَدر",       "Al-Qadr",       SurahOrigin.MECCAN, verseCount = 5),
        Surah(98,  "البَيِّنَة",   "Al-Bayyinah",   SurahOrigin.MEDINAN, verseCount = 8),
        Surah(99,  "الزَّلزَلَة",  "Az-Zalzalah",   SurahOrigin.MEDINAN, verseCount = 8),
        Surah(100, "العَادِيَات",  "Al-'Adiyat",    SurahOrigin.MECCAN, verseCount = 11),
        Surah(101, "القَارِعَة",   "Al-Qari'ah",    SurahOrigin.MECCAN, verseCount = 11),
        Surah(102, "التَّكَاثُر",  "At-Takathur",   SurahOrigin.MECCAN, verseCount = 8),
        Surah(103, "العَصر",       "Al-'Asr",       SurahOrigin.MECCAN, verseCount = 3),
        Surah(104, "الهُمَزَة",    "Al-Humazah",    SurahOrigin.MECCAN, verseCount = 9),
        Surah(105, "الفِيل",       "Al-Fil",        SurahOrigin.MECCAN, verseCount = 5),
        Surah(106, "قُرَيش",       "Quraysh",       SurahOrigin.MECCAN, verseCount = 4),
        Surah(107, "المَاعُون",    "Al-Ma'un",      SurahOrigin.MECCAN, verseCount = 7),
        Surah(108, "الكَوثَر",     "Al-Kawthar",    SurahOrigin.MECCAN, verseCount = 3),
        Surah(109, "الكَافِرُون",  "Al-Kafirun",    SurahOrigin.MECCAN, verseCount = 6),
        Surah(110, "النَّصر",      "An-Nasr",       SurahOrigin.MEDINAN, verseCount = 3),
        Surah(111, "المَسَد",      "Al-Masad",      SurahOrigin.MECCAN, verseCount = 5),
        Surah(112, "الإِخلَاص",    "Al-Ikhlas",     SurahOrigin.MECCAN, verseCount = 4),
        Surah(113, "الفَلَق",      "Al-Falaq",      SurahOrigin.MECCAN, verseCount = 5),
        Surah(114, "النَّاس",      "An-Nas",        SurahOrigin.MECCAN, verseCount = 6),
    )
}
